### PR TITLE
[DO NOT MERGE] Open3d slam tf prior priors

### PR DESCRIPTION
**Pull request by tutunarsl**
Draft for open3d slam tf usage, very naive

### CODE REVIEW

**Comment by nubertj** [comment]
any plans to incorporate this functionality more cleaned-up in the future oin master?

**Comment by tutunarsl** [comment]
> any plans to incorporate this functionality more cleaned-up in the future on master?

Yes, currently 2 users reported unexpected rate drops on the tf publishing. The odom -> map transformation was always delayed. I am currently investigating whether this is a structure issue or a limitation in computation.

Once the core structure is validated I will re-factor with the already existing API and extend the API without conflicts with the current structure.

TLDR; This is WIP, but not forgotten. A proper PR will follow

**Comment by nubertj** [comment]
I also talked to Jonas about this. I think the delay he experienced is expected. Also I could remove the delay on my end.

But your changes look very different from that? I more thought about whether we want to docus on icorporating external priors or even IMU?

**Comment by tutunarsl** [comment]
@nubertj 

https://github.com/leggedrobotics/open3d_slam/blob/6767233d014709f7a497745213aa371500db7019/open3d_slam_ros/src/SlamWrapperRos.cpp#L259

This is the function that accepts  external prior odom->lidar

**Pull request closed without merging**
